### ISSUE TITLE
php artisan sectheater:install error

### ISSUE THREAD

**Issue by s-ebaid** [SecTheater/laravel-jarvis#8]
when i run the command php artisan sectheater:install I get this error:
λ php artisan sectheater:install
Copied Directory [\vendor\sectheater\laravel-jarvis\src\publishable\Database\Migrations] To [\database\migrations]
Copied Directory [\vendor\sectheater\laravel-jarvis\src\publishable\Database\Seeders] To [\database\seeds]
Copied Directory [\vendor\sectheater\laravel-jarvis\src\publishable\Views\Emails] To [\resources\emails]
Copied Directory [\vendor\sectheater\laravel-jarvis\src\publishable\Mail] To [\app\Mail]
Publishing complete.

   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function SecTheater\Jarvis\Commands\posix_getpwuid()

  at E:\xampp\htdocs\edms\vendor\sectheater\laravel-jarvis\src\Commands\InstallCommand.php: 92
    88|                 "\n\n Jarvis::Routes();"
    89|             );
    90|         }
    91|         $this->call('vendor:publish', ['--provider' => JarvisServiceProvider::class]);
  > 92|         $name = posix_getpwuid(posix_getuid())['name'];
    93|         $time = (\Carbon\Carbon::now()->format('A') === 'AM') ? 'Morning' : 'Evening';
    94|         $this->info("Good $time $name , Hopefully you fill up this survey to designate the features within your application");
    95|         $value = $this->choice('Does Your Application contain of Comments,Replies,Posts,Authentication,Tags & Likes ? ', ['Yes', 'No']);
    96|         if ($value === 'No') {

  Exception trace:

  1   SecTheater\Jarvis\Commands\InstallCommand::handle()
      E:\xampp\htdocs\edms\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 29

  2   call_user_func_array([])
      E:\xampp\htdocs\edms\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 29

  Please use the argument -v to see more details.

**Comment by SecTheater** [comment]
Bug Fixed, you have now to run "composer require sectheater/laravel-jarvis:dev-master"
