### ISSUE TITLE
php artisan sectheater:auth Error

### ISSUE THREAD

**Issue by s-ebaid** [SecTheater/laravel-jarvis#9]
php artisan sectheater:auth
Publishing Controllers
[===>------------------------]Controllers namespace is set !
[=======>--------------------]Publishing Custom Validation Rules !

   ErrorException  : mkdir(): No such file or directory

  at E:\xampp\htdocs\edms\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php: 442
    438|         if ($force) {
    439|             return @mkdir($path, $mode, $recursive);
    440|         }
    441|
  > 442|         return mkdir($path, $mode, $recursive);
    443|     }
    444|
    445|     /**
    446|      * Move a directory.

  Exception trace:

  1   mkdir("\app\Rules")
      E:\xampp\htdocs\edms\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php : 442

  2   Illuminate\Filesystem\Filesystem::makeDirectory("\app\Rules")
      E:\xampp\htdocs\edms\vendor\sectheater\laravel-jarvis\src\Commands\CustomValidationCommand.php : 47

  Please use the argument -v to see more details.

**Comment by SecTheater** [comment]
Bug Fixed, I really appreciate reporting this issue.
In order to let the fix take Its effect, please run "composer require sectheater/laravel-jarvis:dev-master"
